### ISSUE TITLE
CSV Data Configuration | Format, etc.

### ISSUE THREAD

**Issue by marvinweber** [micheltokic/stable_baselines_model_based_rl#3]
"Specification" of the configuration file section for the CSV Data File (the file, containing the data to train the dynamic model with).

## Configuration of Action Columns
List including all CSV-Headers of columns, that represent actions.
```yaml
action_cols:
    - A_0
    - A_1
action_type: DISCRETE
discrete_column_sets: null
```
#### Type of Action
Either DISCRETE, MULTI_DISCRETE, or BOX.
For DISCRETE, all action columns represent of of the possible discrete actions. For MULTI_DISCRETE, the `discrete_colum_sets` must be defined (see below). For BOX, the shape must be defined (TBD)

#### Multi Discrete Action
It must be specified, which columns belong to which discrete action:
```yaml
action_cols:
    - A_0_0
    - A_0_1
    - A_1_0
    - A_1_1
    - A_1_2
action_type: MULTI_DISCRETE
discrete_column_sets:
    - [ A_0_0, A_0_1 ]
    - [ A_1_0, A_1_1, A_1_2 ]
```
This configuration would represent a multi discrete action consisting of two discrete actions. The first of which would have two discrete actions (A_0_0, A_0_1), the second would have three discrete actions (A_1_0, A_1_1, A_1_2).

#### Box Actions
tbd
